### ISSUE TITLE
Social Meta Tags

### ISSUE THREAD

**Issue by kera-cudmore** [Mbutler1991/seasonedgreetings#19]
Add Social meta tags to allow nice site images when sharing the page url :) 

- [x] Home Page
- [x] Contact Page
- [x] Thank You Page
- [x] Team Page
- [x] 404 Page
- [x] 500 Page

**Content to be added to:**

- [x] Keyword meta tag
- [x] Description meta tag
- [x] Social description meta tag - to be same as the description meta tag
- [x] Social image url - for the image shown on social
- [x] Social image alt text
- [x] Make sure each social meta url tag is pointing to the correct page
- [x] Social author
- [x] Twitter description - same as description meta tag
- [x] Twitter url
- [x] Twitter alt text

- [x] Social meta og:type content to be changed to website on all pages
